/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UserStoryStandaloneSetup extends UserStoryStandaloneSetupGenerated {

	public static void doSetup() {
		new UserStoryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
