/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.userstory.userStory.UserStoryPackage;
import org.xtext.example.userstory.userStory.usTask;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>us Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class usTaskImpl extends usActivityImpl implements usTask
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected usTaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UserStoryPackage.Literals.US_TASK;
  }

} //usTaskImpl
