/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUserStoryScopeProvider extends DelegatingScopeProvider {
}
