/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.userstory.UserStoryRuntimeModule;
import org.xtext.example.userstory.UserStoryStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UserStoryIdeSetup extends UserStoryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UserStoryRuntimeModule(), new UserStoryIdeModule()));
	}
	
}
