/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.ide;


/**
 * Use this class to register ide components.
 */
public class UserStoryIdeModule extends AbstractUserStoryIdeModule {
}
