/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.example.userstory.userStory.UserStoryFactory;
import org.xtext.example.userstory.userStory.usArtifact;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>us Artifact</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class usArtifactTest extends TestCase {

	/**
	 * The fixture for this us Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected usArtifact fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(usArtifactTest.class);
	}

	/**
	 * Constructs a new us Artifact test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public usArtifactTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this us Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(usArtifact fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this us Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected usArtifact getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UserStoryFactory.eINSTANCE.createusArtifact());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //usArtifactTest
