/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory.tests;

import junit.textui.TestRunner;

import org.xtext.example.userstory.userStory.UserStoryFactory;
import org.xtext.example.userstory.userStory.usEvent;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>us Event</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class usEventTest extends usActivityTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(usEventTest.class);
	}

	/**
	 * Constructs a new us Event test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public usEventTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this us Event test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected usEvent getFixture() {
		return (usEvent)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UserStoryFactory.eINSTANCE.createusEvent());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //usEventTest
