/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory.tests;

import junit.textui.TestRunner;

import org.xtext.example.userstory.userStory.UserStoryFactory;
import org.xtext.example.userstory.userStory.usTask;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>us Task</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class usTaskTest extends usActivityTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(usTaskTest.class);
	}

	/**
	 * Constructs a new us Task test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public usTaskTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this us Task test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected usTask getFixture() {
		return (usTask)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UserStoryFactory.eINSTANCE.createusTask());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //usTaskTest
