/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Us</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getTitre <em>Titre</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getRole <em>Role</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getActivity <em>Activity</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getArtifact <em>Artifact</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getOtherArtifact <em>Other Artifact</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getEvent <em>Event</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getOtherEvent <em>Other Event</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.Us#getOtherActivity <em>Other Activity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs()
 * @model
 * @generated
 */
public interface Us extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Titre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titre</em>' attribute.
   * @see #setTitre(String)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Titre()
   * @model
   * @generated
   */
  String getTitre();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getTitre <em>Titre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titre</em>' attribute.
   * @see #getTitre()
   * @generated
   */
  void setTitre(String value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' containment reference.
   * @see #setRole(Role)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Role()
   * @model containment="true"
   * @generated
   */
  Role getRole();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getRole <em>Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' containment reference.
   * @see #getRole()
   * @generated
   */
  void setRole(Role value);

  /**
   * Returns the value of the '<em><b>Activity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activity</em>' containment reference.
   * @see #setActivity(usActivity)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Activity()
   * @model containment="true"
   * @generated
   */
  usActivity getActivity();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getActivity <em>Activity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activity</em>' containment reference.
   * @see #getActivity()
   * @generated
   */
  void setActivity(usActivity value);

  /**
   * Returns the value of the '<em><b>Artifact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact</em>' containment reference.
   * @see #setArtifact(usArtifact)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Artifact()
   * @model containment="true"
   * @generated
   */
  usArtifact getArtifact();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getArtifact <em>Artifact</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact</em>' containment reference.
   * @see #getArtifact()
   * @generated
   */
  void setArtifact(usArtifact value);

  /**
   * Returns the value of the '<em><b>Other Artifact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other Artifact</em>' containment reference.
   * @see #setOtherArtifact(usArtifact)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_OtherArtifact()
   * @model containment="true"
   * @generated
   */
  usArtifact getOtherArtifact();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getOtherArtifact <em>Other Artifact</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Other Artifact</em>' containment reference.
   * @see #getOtherArtifact()
   * @generated
   */
  void setOtherArtifact(usArtifact value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(usEvent)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_Event()
   * @model containment="true"
   * @generated
   */
  usEvent getEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(usEvent value);

  /**
   * Returns the value of the '<em><b>Other Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other Event</em>' containment reference.
   * @see #setOtherEvent(usEvent)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_OtherEvent()
   * @model containment="true"
   * @generated
   */
  usEvent getOtherEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getOtherEvent <em>Other Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Other Event</em>' containment reference.
   * @see #getOtherEvent()
   * @generated
   */
  void setOtherEvent(usEvent value);

  /**
   * Returns the value of the '<em><b>Other Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other Activity</em>' reference.
   * @see #setOtherActivity(usActivity)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getUs_OtherActivity()
   * @model
   * @generated
   */
  usActivity getOtherActivity();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.Us#getOtherActivity <em>Other Activity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Other Activity</em>' reference.
   * @see #getOtherActivity()
   * @generated
   */
  void setOtherActivity(usActivity value);

} // Us
