/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>us Artifact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.userstory.userStory.usArtifact#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.usArtifact#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.userstory.userStory.usArtifact#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusArtifact()
 * @model
 * @generated
 */
public interface usArtifact extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusArtifact_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.usArtifact#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusArtifact_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.usArtifact#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusArtifact_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.usArtifact#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // usArtifact
