/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.userstory.userStory.UserStoryFactory
 * @model kind="package"
 * @generated
 */
public interface UserStoryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "userStory";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/userstory/UserStory";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "userStory";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UserStoryPackage eINSTANCE = org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.BacklogImpl <em>Backlog</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.BacklogImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getBacklog()
   * @generated
   */
  int BACKLOG = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKLOG__NAME = 0;

  /**
   * The feature id for the '<em><b>Backlog</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKLOG__BACKLOG = 1;

  /**
   * The number of structural features of the '<em>Backlog</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKLOG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.UsImpl <em>Us</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.UsImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getUs()
   * @generated
   */
  int US = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__ID = 0;

  /**
   * The feature id for the '<em><b>Titre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__TITRE = 1;

  /**
   * The feature id for the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__ROLE = 2;

  /**
   * The feature id for the '<em><b>Activity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__ACTIVITY = 3;

  /**
   * The feature id for the '<em><b>Artifact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__ARTIFACT = 4;

  /**
   * The feature id for the '<em><b>Other Artifact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__OTHER_ARTIFACT = 5;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__EVENT = 6;

  /**
   * The feature id for the '<em><b>Other Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__OTHER_EVENT = 7;

  /**
   * The feature id for the '<em><b>Other Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US__OTHER_ACTIVITY = 8;

  /**
   * The number of structural features of the '<em>Us</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.usActivityImpl <em>us Activity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.usActivityImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusActivity()
   * @generated
   */
  int US_ACTIVITY = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ACTIVITY__ID = 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ACTIVITY__REF = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ACTIVITY__NAME = 2;

  /**
   * The number of structural features of the '<em>us Activity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ACTIVITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.usTaskImpl <em>us Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.usTaskImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusTask()
   * @generated
   */
  int US_TASK = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_TASK__ID = US_ACTIVITY__ID;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_TASK__REF = US_ACTIVITY__REF;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_TASK__NAME = US_ACTIVITY__NAME;

  /**
   * The number of structural features of the '<em>us Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_TASK_FEATURE_COUNT = US_ACTIVITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.usEventImpl <em>us Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.usEventImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusEvent()
   * @generated
   */
  int US_EVENT = 4;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_EVENT__ID = US_ACTIVITY__ID;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_EVENT__REF = US_ACTIVITY__REF;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_EVENT__NAME = US_ACTIVITY__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_EVENT__TYPE = US_ACTIVITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>us Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_EVENT_FEATURE_COUNT = US_ACTIVITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.usArtifactImpl <em>us Artifact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.usArtifactImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusArtifact()
   * @generated
   */
  int US_ARTIFACT = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ARTIFACT__ID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ARTIFACT__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ARTIFACT__TYPE = 2;

  /**
   * The number of structural features of the '<em>us Artifact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int US_ARTIFACT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.userstory.userStory.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.userstory.userStory.impl.RoleImpl
   * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getRole()
   * @generated
   */
  int ROLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.Backlog <em>Backlog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backlog</em>'.
   * @see org.xtext.example.userstory.userStory.Backlog
   * @generated
   */
  EClass getBacklog();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.Backlog#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.userstory.userStory.Backlog#getName()
   * @see #getBacklog()
   * @generated
   */
  EAttribute getBacklog_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.userstory.userStory.Backlog#getBacklog <em>Backlog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Backlog</em>'.
   * @see org.xtext.example.userstory.userStory.Backlog#getBacklog()
   * @see #getBacklog()
   * @generated
   */
  EReference getBacklog_Backlog();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.Us <em>Us</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Us</em>'.
   * @see org.xtext.example.userstory.userStory.Us
   * @generated
   */
  EClass getUs();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.Us#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getId()
   * @see #getUs()
   * @generated
   */
  EAttribute getUs_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.Us#getTitre <em>Titre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titre</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getTitre()
   * @see #getUs()
   * @generated
   */
  EAttribute getUs_Titre();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Role</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getRole()
   * @see #getUs()
   * @generated
   */
  EReference getUs_Role();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getActivity <em>Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Activity</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getActivity()
   * @see #getUs()
   * @generated
   */
  EReference getUs_Activity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getArtifact <em>Artifact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Artifact</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getArtifact()
   * @see #getUs()
   * @generated
   */
  EReference getUs_Artifact();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getOtherArtifact <em>Other Artifact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Other Artifact</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getOtherArtifact()
   * @see #getUs()
   * @generated
   */
  EReference getUs_OtherArtifact();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getEvent()
   * @see #getUs()
   * @generated
   */
  EReference getUs_Event();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.userstory.userStory.Us#getOtherEvent <em>Other Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Other Event</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getOtherEvent()
   * @see #getUs()
   * @generated
   */
  EReference getUs_OtherEvent();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.userstory.userStory.Us#getOtherActivity <em>Other Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Other Activity</em>'.
   * @see org.xtext.example.userstory.userStory.Us#getOtherActivity()
   * @see #getUs()
   * @generated
   */
  EReference getUs_OtherActivity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.usActivity <em>us Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>us Activity</em>'.
   * @see org.xtext.example.userstory.userStory.usActivity
   * @generated
   */
  EClass getusActivity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usActivity#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.userstory.userStory.usActivity#getId()
   * @see #getusActivity()
   * @generated
   */
  EAttribute getusActivity_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usActivity#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref</em>'.
   * @see org.xtext.example.userstory.userStory.usActivity#getRef()
   * @see #getusActivity()
   * @generated
   */
  EAttribute getusActivity_Ref();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usActivity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.userstory.userStory.usActivity#getName()
   * @see #getusActivity()
   * @generated
   */
  EAttribute getusActivity_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.usTask <em>us Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>us Task</em>'.
   * @see org.xtext.example.userstory.userStory.usTask
   * @generated
   */
  EClass getusTask();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.usEvent <em>us Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>us Event</em>'.
   * @see org.xtext.example.userstory.userStory.usEvent
   * @generated
   */
  EClass getusEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usEvent#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.userstory.userStory.usEvent#getType()
   * @see #getusEvent()
   * @generated
   */
  EAttribute getusEvent_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.usArtifact <em>us Artifact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>us Artifact</em>'.
   * @see org.xtext.example.userstory.userStory.usArtifact
   * @generated
   */
  EClass getusArtifact();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usArtifact#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.userstory.userStory.usArtifact#getId()
   * @see #getusArtifact()
   * @generated
   */
  EAttribute getusArtifact_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usArtifact#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.userstory.userStory.usArtifact#getName()
   * @see #getusArtifact()
   * @generated
   */
  EAttribute getusArtifact_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.usArtifact#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.userstory.userStory.usArtifact#getType()
   * @see #getusArtifact()
   * @generated
   */
  EAttribute getusArtifact_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.userstory.userStory.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.example.userstory.userStory.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.userstory.userStory.Role#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.userstory.userStory.Role#getName()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UserStoryFactory getUserStoryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.BacklogImpl <em>Backlog</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.BacklogImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getBacklog()
     * @generated
     */
    EClass BACKLOG = eINSTANCE.getBacklog();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKLOG__NAME = eINSTANCE.getBacklog_Name();

    /**
     * The meta object literal for the '<em><b>Backlog</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BACKLOG__BACKLOG = eINSTANCE.getBacklog_Backlog();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.UsImpl <em>Us</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.UsImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getUs()
     * @generated
     */
    EClass US = eINSTANCE.getUs();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US__ID = eINSTANCE.getUs_Id();

    /**
     * The meta object literal for the '<em><b>Titre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US__TITRE = eINSTANCE.getUs_Titre();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__ROLE = eINSTANCE.getUs_Role();

    /**
     * The meta object literal for the '<em><b>Activity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__ACTIVITY = eINSTANCE.getUs_Activity();

    /**
     * The meta object literal for the '<em><b>Artifact</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__ARTIFACT = eINSTANCE.getUs_Artifact();

    /**
     * The meta object literal for the '<em><b>Other Artifact</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__OTHER_ARTIFACT = eINSTANCE.getUs_OtherArtifact();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__EVENT = eINSTANCE.getUs_Event();

    /**
     * The meta object literal for the '<em><b>Other Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__OTHER_EVENT = eINSTANCE.getUs_OtherEvent();

    /**
     * The meta object literal for the '<em><b>Other Activity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference US__OTHER_ACTIVITY = eINSTANCE.getUs_OtherActivity();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.usActivityImpl <em>us Activity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.usActivityImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusActivity()
     * @generated
     */
    EClass US_ACTIVITY = eINSTANCE.getusActivity();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ACTIVITY__ID = eINSTANCE.getusActivity_Id();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ACTIVITY__REF = eINSTANCE.getusActivity_Ref();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ACTIVITY__NAME = eINSTANCE.getusActivity_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.usTaskImpl <em>us Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.usTaskImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusTask()
     * @generated
     */
    EClass US_TASK = eINSTANCE.getusTask();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.usEventImpl <em>us Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.usEventImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusEvent()
     * @generated
     */
    EClass US_EVENT = eINSTANCE.getusEvent();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_EVENT__TYPE = eINSTANCE.getusEvent_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.usArtifactImpl <em>us Artifact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.usArtifactImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getusArtifact()
     * @generated
     */
    EClass US_ARTIFACT = eINSTANCE.getusArtifact();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ARTIFACT__ID = eINSTANCE.getusArtifact_Id();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ARTIFACT__NAME = eINSTANCE.getusArtifact_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute US_ARTIFACT__TYPE = eINSTANCE.getusArtifact_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.userstory.userStory.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.userstory.userStory.impl.RoleImpl
     * @see org.xtext.example.userstory.userStory.impl.UserStoryPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__NAME = eINSTANCE.getRole_Name();

  }

} //UserStoryPackage
