/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.userstory.userStory.UserStoryPackage
 * @generated
 */
public interface UserStoryFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UserStoryFactory eINSTANCE = org.xtext.example.userstory.userStory.impl.UserStoryFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Backlog</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Backlog</em>'.
   * @generated
   */
  Backlog createBacklog();

  /**
   * Returns a new object of class '<em>Us</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Us</em>'.
   * @generated
   */
  Us createUs();

  /**
   * Returns a new object of class '<em>us Activity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>us Activity</em>'.
   * @generated
   */
  usActivity createusActivity();

  /**
   * Returns a new object of class '<em>us Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>us Task</em>'.
   * @generated
   */
  usTask createusTask();

  /**
   * Returns a new object of class '<em>us Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>us Event</em>'.
   * @generated
   */
  usEvent createusEvent();

  /**
   * Returns a new object of class '<em>us Artifact</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>us Artifact</em>'.
   * @generated
   */
  usArtifact createusArtifact();

  /**
   * Returns a new object of class '<em>Role</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Role</em>'.
   * @generated
   */
  Role createRole();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UserStoryPackage getUserStoryPackage();

} //UserStoryFactory
