/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>us Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.userstory.userStory.usEvent#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusEvent()
 * @model
 * @generated
 */
public interface usEvent extends usActivity
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(int)
   * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusEvent_Type()
   * @model
   * @generated
   */
  int getType();

  /**
   * Sets the value of the '{@link org.xtext.example.userstory.userStory.usEvent#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(int value);

} // usEvent
