/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.userStory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>us Task</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.userstory.userStory.UserStoryPackage#getusTask()
 * @model
 * @generated
 */
public interface usTask extends usActivity
{
} // usTask
