/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UserStoryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/userstory/parser/antlr/internal/InternalUserStory.tokens");
	}
}
