/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.userstory.ui.internal.UserstoryActivator;

public class UserStoryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UserstoryActivator.getInstance().getInjector("org.xtext.example.userstory.UserStory");
	}

}
