/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UserStoryUiModule extends AbstractUserStoryUiModule {

	public UserStoryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
